//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoopLinq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorted
    {
        public double ID { get; set; }
        public string FileName { get; set; }
        public string Class { get; set; }
    }
}
